### ISSUE TITLE
Tinder::Connection ssl should allow passing any ssl_options to Faraday - fails

### ISSUE THREAD

**Issue by hggh** [collectiveidea/tinder#70]
while testing your library tinder for Debian, with the following dependencies:

ruby2.1 (2.1.2-2)
ruby (1:2.1.0.1)
ruby-diff-lcs (1.2.5-1)
ruby-fakeweb (1.3.0+git20131202.48208f9+dfsg-1)
ruby-multipart-post (1.2.0-2)
ruby-faraday (0.9.0-2)
ruby-faraday-middleware (0.9.1-1)
ruby-hashie (2.0.5-1)
ruby-mime-types (1.25-2)
ruby-multi-json (1.10.0-1)
ruby-rspec-expectations (2.14.2-1)
ruby-rspec-mocks (2.14.5-1)
ruby-rspec-core (2.14.7-2)
ruby-rspec (2.14.1-1)
ruby-simple-oauth (0.2.0-2)
ruby-eventmachine (1.0.3-6+b1)
ruby-http-parser.rb (0.6.0-2+b2)
ruby-json (1.8.1-1+b1)
ruby-twitter-stream (0.1.16-1)

the following error happens:

```
Failures:

  1) Tinder::Connection ssl should allow passing any ssl_options to Faraday
     Failure/Error: connection.connection.ssl.should eql(:verify => false, :ca_path => "/usr/lib/ssl/certs", :ca_file => "/etc/ssl/custom")

       expected: {:verify=>false, :ca_path=>"/usr/lib/ssl/certs", :ca_file=>"/etc/ssl/custom"}
            got: #<Faraday::SSLOptions ca_file="/etc/ssl/custom", ca_path="/usr/lib/ssl/certs">

       (compared using eql?)

       Diff:
       @@ -1,4 +1,13 @@
       -:ca_file => "/etc/ssl/custom",
       -:ca_path => "/usr/lib/ssl/certs",
       -:verify => false
       +#<struct Faraday::SSLOptions
       + verify=false,
       + ca_file="/etc/ssl/custom",
       + ca_path="/usr/lib/ssl/certs",
       + verify_mode=nil,
       + cert_store=nil,
       + client_cert=nil,
       + client_key=nil,
       + certificate=nil,
       + private_key=nil,
       + verify_depth=nil,
       + version=nil>
     # /usr/lib/ruby/vendor_ruby/rspec/expectations/fail_with.rb:32:in `fail_with'
     # /usr/lib/ruby/vendor_ruby/rspec/expectations/handler.rb:34:in `handle_matcher'
     # /usr/lib/ruby/vendor_ruby/rspec/expectations/syntax.rb:53:in `should'
     # ./spec/tinder/connection_spec.rb:101:in `block (3 levels) in <top (required)>'
     # /usr/lib/ruby/vendor_ruby/rspec/core/example.rb:114:in `instance_eval'
     # /usr/lib/ruby/vendor_ruby/rspec/core/example.rb:114:in `block in run'
     # /usr/lib/ruby/vendor_ruby/rspec/core/example.rb:254:in `with_around_each_hooks'
     # /usr/lib/ruby/vendor_ruby/rspec/core/example.rb:111:in `run'
     # /usr/lib/ruby/vendor_ruby/rspec/core/example_group.rb:390:in `block in run_examples'
     # /usr/lib/ruby/vendor_ruby/rspec/core/example_group.rb:386:in `map'
     # /usr/lib/ruby/vendor_ruby/rspec/core/example_group.rb:386:in `run_examples'
     # /usr/lib/ruby/vendor_ruby/rspec/core/example_group.rb:371:in `run'
     # /usr/lib/ruby/vendor_ruby/rspec/core/example_group.rb:372:in `block in run'
     # /usr/lib/ruby/vendor_ruby/rspec/core/example_group.rb:372:in `map'
     # /usr/lib/ruby/vendor_ruby/rspec/core/example_group.rb:372:in `run'
     # /usr/lib/ruby/vendor_ruby/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /usr/lib/ruby/vendor_ruby/rspec/core/command_line.rb:28:in `map'
     # /usr/lib/ruby/vendor_ruby/rspec/core/command_line.rb:28:in `block in run'
     # /usr/lib/ruby/vendor_ruby/rspec/core/reporter.rb:58:in `report'
     # /usr/lib/ruby/vendor_ruby/rspec/core/command_line.rb:25:in `run'
     # /usr/lib/ruby/vendor_ruby/rspec/core/runner.rb:80:in `run'
     # /usr/lib/ruby/vendor_ruby/rspec/core/runner.rb:17:in `block in autorun'

Finished in 0.10882 seconds
51 examples, 1 failure

Failed examples:

rspec ./spec/tinder/connection_spec.rb:88 # Tinder::Connection ssl should allow passing any ssl_options to Faraday
/usr/bin/ruby2.1 -S rspec ./spec/tinder/campfire_spec.rb ./spec/tinder/connection_spec.rb ./spec/tinder/room_spec.rb failed
```

Could you please have a look?

**Comment by asheren** [comment]
Hi there! We're doing some open source maintenance work and closing old issues. If this issue is still applicable or you would still like it to be addressed, please re-open the issue by April 17, 2017. Thanks!
